trigger:
  - master
  # - feature/*
  
resources:
  - repo: self
  
variables:
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: 'acr-connection'
    imageRepository: 'bootcamp-app'
    containerRegistry: 'bootcampappcontainer.azurecr.io'
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: '$(Build.BuildId)'
  
    # Agent VM image name
    vmImageName: 'ubuntu-latest'
  
stages:
  - stage: CI
    displayName: Build and push 
    jobs:
    - job:
      displayName: Run npm install
      pool: 
        name: bootcamp-app-pool
        vmImage: $(vmImageName)
      steps:
        - task: Npm@1
          displayName: npm install
          inputs:
            command: 'install'
            workingDir: '$(Build.SourcesDirectory)'

    - job: Build
      displayName: Build
      pool:
        name: bootcamp-app-pool
        vmImage: $(vmImageName)
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: $(dockerRegistryServiceConnection)
          command: buildAndPush
          repository: $(imageRepository)
          Dockerfile: $(dockerfilePath)
          tags: |
            $(tag)
      - task: PublishBuildArtifacts@1
        displayName: Artifact the container.
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/'
          ArtifactName: 'bootcamp-app' 
          publishLocation: 'Container' 

           

      