apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeweighttracker-app
  labels:
    app: nodeweighttracker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeweighttracker-app
  template:
    metadata:
      name: nodeweighttracker-app
      labels:
        app: nodeweighttracker-app
    spec:
      containers:
      - name: nodeweighttracker-app
        image: bootcampappcontainer.azurecr.io/bootcamp-app:199
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: PORT
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: HOST
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: NODE_ENV
          - name: HOST_URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: HOST_URL
          - name: OKTA_ORG_URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: OKTA_ORG_URL
          - name:  PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key:  PGDATABASE   
          - name:  PGPORT
            valueFrom:
              configMapKeyRef:
                name: env-config
                key:  PGPORT 
          - name: COOKIE_ENCRYPT_PWD
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: COOKIE_ENCRYPT_PWD
          - name: OKTA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: OKTA_CLIENT_ID
          - name: OKTA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: OKTA_CLIENT_SECRET
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: PGHOST
          - name: PGUSERNAME
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: PGUSERNAME
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: PGPASSWORD